# Generated by Django 5.2.1 on 2025-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
