# Generated by Django 5.2.1 on 2025-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_testimonial_alter_emp_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
